# Generated by Django 3.2.7 on 2021-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
