# Generated by Django 3.2.7 on 2021-09-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profilemodel_avalability'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='birhday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='誕生日'),
            preserve_default=False,
        ),
    ]
