# Generated by Django 3.2.7 on 2021-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profilemodel_birhday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birhday',
            field=models.DateField(),
        ),
    ]
